spring.datasource.url=jdbc:mysql://localhost:3306/smart_clinic?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=ThisIsASecretKeyForJWTSigningAndItMustBeLongEnough1234567890
